version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.1
workflows:
  build:
    jobs:
        - cypress/run:
            cypress-command: npx cypress run --parallel
            parallel: true
            parallelism: 2
            group: 2 machines